# Docker Compose for local development and testing
version: '3.8'

services:
  loan-predictor:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
